import type { Metadata } from "next";
import "./globals.css";
import Header from "./Header";
import Footer from "./Footer";

export const metadata: Metadata = {
  title: "Hakase",
  description: "Generated by Hakase",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="h-screen flex flex-col">
          <Header />
          <main className="container mx-auto flex-grow p-2 flex flex-col items-center">
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
